apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    %SKIPRANGELINE%
  name: testoperator.v%VERSION%
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Testoperator
  install:
    spec:
      deployments:
      - name: testoperator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: testoperator
          strategy: {}
          template:
            metadata:
              labels:
                name: testoperator
            spec:
              containers:
              - command:
                - testoperator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: testoperator
                - name: RELATED_IMAGE_OPERAND1
                  value: REPLACE_IMAGE_OPERAND1
                - name: RELATED_IMAGE_OPERAND2
                  value: REPLACE_IMAGE_OPERAND2
                image: REPLACE_IMAGE_CONTROLLER
                imagePullPolicy: Always
                name: testoperator
                resources: {}
              serviceAccountName: testoperator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - testoperator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        serviceAccountName: testoperator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  %REPLACESLINE%
  version: %VERSION%
  relatedImages:
  - name: RELATED_IMAGE_OPERAND1
    image: REPLACE_IMAGE_OPERAND1
  - name: RELATED_IMAGE_OPERAND2
    image: REPLACE_IMAGE_OPERAND2
