apiVersion: apps/v1
kind: Deployment
metadata:
  name: testoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testoperator
  template:
    metadata:
      labels:
        name: testoperator
    spec:
      serviceAccountName: testoperator
      containers:
        - name: testoperator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - testoperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "testoperator"
